version: '3.6'

services:

  pg:
    image: postgres:$POSTGRES_VERSION
    environment:
      - 'POSTGRES_DB=$POSTGRES_DB'
      - 'POSTGRES_USER=$POSTGRES_USER'
      - 'POSTGRES_PASSWORD=$POSTGRES_PASSWORD'
    volumes:
      - pg-data-volume:/var/lib/postgresql/data
      - ./docker/pg/create-users.sql:/docker-entrypoint-initdb.d/create-users.sql
    command: -c log_min_messages=FATAL


  redis:
    image: redis:6.0.9


  mail:
    # Mailhog is a dummy mail server which is useful for testing.
    image: mailhog/mailhog:v1.0.1
    ports:
      - $MAILHOG_LOCAL_PORT:8025


  nginx:
    image: nginx:1.19.4
    volumes:
      - './docker/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './docker/nginx/templates:/etc/nginx/templates'
      - './docker/nginx/ssl/cert.pem:/etc/nginx/ssl/cert.pem'
      - './docker/nginx/ssl/key.pem:/etc/nginx/ssl/key.pem'
    ports:
      - $DEBTORS_PORT:$DEBTORS_PORT
    environment:
      - 'NGINX_ENTRYPOINT_QUIET_LOGS=1'
      - 'USER_FACING_HOSTNAME=$DEBTORS_HOSTNAME'
      - 'USER_FACING_PORT=$DEBTORS_PORT'
      - 'HYDRA_URL=http://login:4444'
      - 'LOGIN_URL=http://login:8080'
      - 'RESOURCE_SERVER_URL=http://resource-server:8080'
      - 'SWAGGER_UI_URL=http://swagger-ui:8080'
    depends_on:
      - login
      - resource-server
      - swagger-ui


  login:
    build:
      context: ./submodules/swpt_login
      dockerfile: Dockerfile
    environment:
      - 'SERVE_PUBLIC_PORT=4444'
      - 'SERVE_ADMIN_PORT=4445'
      - 'WEBSERVER_PORT=8080'
      - 'LOGIN_PATH=/debtors-login'
      - 'CONSENT_PATH=/debtors-consent'
      - 'SUBJECT_PREFIX=debtors:'
      - 'SECRETS_SYSTEM=$HYDRA_SYSTEM_SECRET'
      - 'SERVE_TLS_ALLOW_TERMINATION_FROM=0.0.0.0/0'
      - 'URLS_SELF_ISSUER=https://$DEBTORS_HOSTNAME:$DEBTORS_PORT'
      - 'URLS_ERROR=https://github.com/epandurski/swpt_login'
      - 'HYDRA_DSN=postgres://hydra:hydra@pg/${POSTGRES_DB}?sslmode=disable'
      - 'SQLALCHEMY_DATABASE_URI=postgresql://swpt_debtors_login:swpt_debtors_login@pg/${POSTGRES_DB}'
      - 'REDIS_URL=redis://redis:6379/0?health_check_interval=30'
      - 'HYDRA_ADMIN_URL=http://login:4445'
      - 'SITE_TITLE=Swaptacular'
      - 'STYLE_URL='
      - 'ABOUT_URL=https://github.com/epandurski/swpt_login'
      - 'RECAPTCHA_PUBLIC_KEY=6Lc902MUAAAAAJL22lcbpY3fvg3j4LSERDDQYe37'
      - 'RECAPTCHA_PIVATE_KEY=6Lc902MUAAAAAN--r4vUr8Vr7MU1PF16D9k2Ds9Q'
      - 'MAIL_SERVER=mail'
      - 'MAIL_PORT=1025'
      - 'MAIL_USE_TLS=False'
      - 'MAIL_USE_SSL=False'
      - 'MAIL_USERNAME=None'
      - 'MAIL_PASSWORD=None'
      - 'MAIL_DEFAULT_SENDER=Swaptacular <no-reply@example.com>'
      - 'API_AUTH2_TOKEN_URL=https://nginx:$DEBTORS_PORT/oauth2/token'
      - 'API_RESOURCE_SERVER=http://resource-server:8080'
      - 'API_RESERVE_USER_ID_PATH=/debtors/.debtor-reserve'
      - 'API_USER_ID_FIELD_NAME=debtorId'
      - 'API_TIMEOUT_SECONDS=5'
      - 'SUPERVISOR_CLIENT_ID=debtors-supervisor'
      - 'SUPERVISOR_CLIENT_SECRET=debtors-supervisor'
      - 'WEBSERVER_LOGLEVEL=warning'
      - 'WEBSERVER_WORKERS=1'
      - 'WEBSERVER_THREADS=3'
    depends_on:
      - pg
      - redis
      - mail


  login-config:
    build:
      context: ./submodules/swpt_login
      dockerfile: Dockerfile
    environment:
      - 'HYDRA_DSN=postgres://hydra:hydra@pg/${POSTGRES_DB}?sslmode=disable'
      - 'SQLALCHEMY_DATABASE_URI=postgresql://swpt_debtors_login:swpt_debtors_login@pg/${POSTGRES_DB}'
    command: configure
    depends_on:
      - pg


  hydra-config:
    build:
      context: ./submodules/swpt_login
      dockerfile: Dockerfile
    environment:
      - 'HYDRA_ADMIN_URL=http://login:4445'
    volumes:
      - './docker/hydra:/etc/hydra-config'
    command:
      hydra clients import
      /etc/hydra-config/debtors-supervisor.json
      /etc/hydra-config/swagger-ui.json
      --fake-tls-termination
      --fail-after 5m
    depends_on:
      - login


  resource-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-image
    environment:
      - 'PORT=8080'
      - 'OAUTH2_INTROSPECT_URL=http://login:4445/oauth2/introspect'
      - 'SQLALCHEMY_DATABASE_URI=postgresql://swpt_debtors:swpt_debtors@pg:5432/${POSTGRES_DB}'
      - 'WEBSERVER_LOGLEVEL=warning'
      - 'WEBSERVER_WORKERS=1'
      - 'WEBSERVER_THREADS=3'
      - 'PROTOCOL_BROKER_URL=amqp://guest:guest@localhost:5672'
      - 'PROTOCOL_PROCESSES=1'
      - 'PROTOCOL_THREADS=3'
    depends_on:
      - pg


  resource-server-config:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-image
    environment:
      - 'SQLALCHEMY_DATABASE_URI=postgresql://swpt_debtors:swpt_debtors@pg:5432/${POSTGRES_DB}'
      - 'PROTOCOL_BROKER_URL=amqp://guest:guest@localhost:5672'
      - 'MIN_DEBTOR_ID=4294967296'
      - 'MAX_DEBTOR_ID=8589934591'
    command: configure
    depends_on:
      - pg


  swagger-ui:
    build:
      context: .
      dockerfile: Dockerfile
      target: swagger-ui-image
    environment:
      - 'BASE_URL=/swagger-ui'
      - 'API_ROOT=https://$DEBTORS_HOSTNAME:$DEBTORS_PORT/'
      - 'OAUTH2_AUTHORIZATION_URL=https://$DEBTORS_HOSTNAME:$DEBTORS_PORT/oauth2/auth'
      - 'OAUTH2_TOKEN_URL=https://$DEBTORS_HOSTNAME:$DEBTORS_PORT/oauth2/token'
      - 'OAUTH2_REFRESH_URL=https://$DEBTORS_HOSTNAME:$DEBTORS_PORT/oauth2/token'
      - 'OAUTH2_REDIRECT_URL=https://$DEBTORS_HOSTNAME:$DEBTORS_PORT/swagger-ui/oauth2-redirect.html'
    depends_on:
      - login
      - resource-server


volumes:
  pg-data-volume:
