version: '3.6'

services:

  pg:
    image: postgres:$POSTGRES_VERSION
    environment:
      - 'POSTGRES_DB=$POSTGRES_DB'
      - 'POSTGRES_USER=$POSTGRES_USER'
      - 'POSTGRES_PASSWORD=$POSTGRES_PASSWORD'
    volumes:
      - pg-data-volume:/var/lib/postgresql/data
      - ./docker/pg/create-users.sql:/docker-entrypoint-initdb.d/create-users.sql


  redis:
    image: redis:6.0.9


  mail:
    # Mailhog is a dummy mail server which is useful for testing.
    image: mailhog/mailhog:v1.0.1
    ports:
      - $MAILHOG_LOCAL_PORT:8025


  nginx:
    image: nginx:1.19.4
    volumes:
      - './docker/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './docker/nginx/templates:/etc/nginx/templates'
      - './docker/nginx/ssl/cert.pem:/etc/nginx/ssl/cert.pem'
      - './docker/nginx/ssl/key.pem:/etc/nginx/ssl/key.pem'
    ports:
      - $DEBTORS_PORT:$DEBTORS_PORT
    environment:
      - 'USER_FACING_HOSTNAME=$DEBTORS_HOSTNAME'
      - 'USER_FACING_PORT=$DEBTORS_PORT'
      - 'HYDRA_URL=http://hydra:4444'
      - 'LOGIN_URL=http://login:8080'
      - 'RESOURCE_SERVER_URL=http://resource-server:8080'
      - 'SWAGGER_UI_URL=http://swagger-ui:8080'
    depends_on:
      - hydra
      - login
      - resource-server
      - swagger-ui


  hydra:
    image: oryd/hydra:$HYDRA_VERSION
    command:
      serve all --dangerous-force-http
    environment:
      - 'DSN=postgres://hydra:hydra@pg/${POSTGRES_DB}?sslmode=disable'
      - 'SECRETS_SYSTEM=$HYDRA_SYSTEM_SECRET'
      - 'SERVE_PUBLIC_PORT=4444'
      - 'SERVE_PUBLIC_CORS_ENABLED=true'
      - 'SERVE_PUBLIC_CORS_DEBUG=false'
      - 'SERVE_PUBLIC_CORS_ALLOWED_ORIGINS=*'
      - 'SERVE_PUBLIC_CORS_ALLOWED_HEADERS=Authorization,Content-Type,X-Requested-With'
      - 'SERVE_PUBLIC_CORS_MAX_AGE=86400'
      - 'SERVE_ADMIN_PORT=4445'
      - 'URLS_SELF_ISSUER=https://$DEBTORS_HOSTNAME:$DEBTORS_PORT'
      - 'URLS_LOGIN=https://$DEBTORS_HOSTNAME:$DEBTORS_PORT/login'
      - 'URLS_CONSENT=https://$DEBTORS_HOSTNAME:$DEBTORS_PORT/consent'
      - 'LOG_LEVEL=warn'
      - 'LOG_FORMAT=json'
      - 'LOG_LEAK_SENSITIVE_VALUES=false'
      - 'OAUTH2_EXPOSE_INTERNAL_ERRORS=true'
      - 'SQA_OPT_OUT=true'
    depends_on:
      - pg
    restart: on-failure


  hydra-migrate:
    image: oryd/hydra:$HYDRA_VERSION
    command:
      migrate sql postgres://hydra:hydra@pg/${POSTGRES_DB}?sslmode=disable --yes
    depends_on:
      - pg
    restart: on-failure


  hydra-config:
    image: oryd/hydra:$HYDRA_VERSION
    environment:
      - 'HYDRA_ADMIN_URL=http://hydra:4445'
    volumes:
      - './docker/hydra:/etc/hydra-config'
    command:
      clients import --fail-after 2m /etc/hydra-config/debtors-supervisor.json /etc/hydra-config/swagger-ui.json
    depends_on:
      - hydra


  login:
    build:
      context: ./submodules/swpt_login
      dockerfile: Dockerfile
    environment:
      - 'PORT=8080'
      - 'SQLALCHEMY_DATABASE_URI=postgresql://swpt_login:swpt_login@pg/${POSTGRES_DB}'
      - 'REDIS_URL=redis://redis:6379/0'
      - 'HYDRA_ADMIN_URL=http://hydra:4445'
      - 'MAIL_SERVER=mail'
      - 'MAIL_PORT=1025'
      - 'MAIL_DEFAULT_SENDER=Swaptacular <no-reply@example.com>'
      - 'GUNICORN_LOGLEVEL=warning'
      - 'GUNICORN_WORKER_CLASS=sync'
      - 'GUNICORN_WORKERS=2'
      - 'GUNICORN_THREADS=1'
      - 'SUPERVISOR_CLIENT_ID=debtors-supervisor'
      - 'SUPERVISOR_CLIENT_SECRET=debtors-supervisor'
      - 'API_AUTH2_TOKEN_URL=http://hydra:4444/oauth2/token'
      - 'API_RESOURCE_SERVER=http://resource-server:8080'
      - 'API_RESERVE_USER_ID_PATH=/debtors/.debtor-reserve'
      - 'API_USER_ID_FIELD_NAME=debtorId'
      - 'API_TIMEOUT_SECONDS=5'
      - 'SUBJECT_PREFIX=debtors:'
      - 'OAUTHLIB_INSECURE_TRANSPORT=1'
    depends_on:
      - pg
      - redis
      - hydra
      - mail


  login-config:
    build:
      context: ./submodules/swpt_login
      dockerfile: Dockerfile
    environment:
      - 'SQLALCHEMY_DATABASE_URI=postgresql://swpt_login:swpt_login@pg/${POSTGRES_DB}'
    command: configure
    depends_on:
      - pg
    restart: on-failure


  resource-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-image
    environment:
      - 'PORT=8080'
      - 'OAUTH2_INTROSPECT_URL=http://hydra:4445/oauth2/introspect'
      - 'SQLALCHEMY_DATABASE_URI=postgresql://swpt_debtors:swpt_debtors@pg:5432/${POSTGRES_DB}'
      - 'GUNICORN_LOGLEVEL=warning'
      - 'GUNICORN_WORKER_CLASS=sync'
      - 'GUNICORN_WORKERS=2'
      - 'GUNICORN_THREADS=1'
      - 'DRAMATIQ_BROKER_URL=amqp://guest:guest@localhost:5672'
      - 'DRAMATIQ_PROCESSES=4'
      - 'DRAMATIQ_THREADS=8'
    depends_on:
      - pg


  resource-server-config:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-image
    environment:
      - 'SQLALCHEMY_DATABASE_URI=postgresql://swpt_debtors:swpt_debtors@pg:5432/${POSTGRES_DB}'
      - 'DRAMATIQ_BROKER_URL=amqp://guest:guest@localhost:5672'
      - 'MIN_DEBTOR_ID=4294967296'
      - 'MAX_DEBTOR_ID=8589934591'
    command: configure
    depends_on:
      - pg


  swagger-ui:
    build:
      context: .
      dockerfile: Dockerfile
      target: swagger-ui-image
    environment:
      - 'BASE_URL=/swagger-ui'
      - 'API_ROOT=https://$DEBTORS_HOSTNAME:$DEBTORS_PORT/'
      - 'OAUTH2_AUTHORIZATION_URL=https://$DEBTORS_HOSTNAME:$DEBTORS_PORT/oauth2/auth'
      - 'OAUTH2_TOKEN_URL=https://$DEBTORS_HOSTNAME:$DEBTORS_PORT/oauth2/token'
      - 'OAUTH2_REFRESH_URL=https://$DEBTORS_HOSTNAME:$DEBTORS_PORT/oauth2/token'
      - 'OAUTH2_REDIRECT_URL=https://$DEBTORS_HOSTNAME:$DEBTORS_PORT/swagger-ui/oauth2-redirect.html'
    depends_on:
      - hydra
      - resource-server


volumes:
  pg-data-volume:
