version: '3.6'

services:

  tests-pg:
    image: postgres:$POSTGRES_VERSION
    environment:
      - 'POSTGRES_DB=$POSTGRES_DB'
      - 'POSTGRES_USER=$POSTGRES_USER'
      - 'POSTGRES_PASSWORD=$POSTGRES_PASSWORD'
    ports:
      - $POSTGRES_LOCAL_PORT:5432


  tests-web:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-image
    volumes:
      - './swpt_debtors:/usr/src/app/swpt_debtors'
    env_file: .env
    environment:
      - 'PORT=8080'
      - 'PYTHONDONTWRITEBYTECODE=1'
      - 'PYTHONBREAKPOINT=web_pdb.set_trace'
      - 'SQLALCHEMY_DATABASE_URI=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@tests-pg:5432/${POSTGRES_DB}'
    ports:
      - $PORT:8080
    command: develop-run-flask
    depends_on:
      - tests-config


  tests-config:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-image
    volumes:
      - './swpt_debtors:/usr/src/app/swpt_debtors'
    env_file: .env
    environment:
      - 'PYTHONDONTWRITEBYTECODE=1'
      - 'SQLALCHEMY_DATABASE_URI=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@tests-pg:5432/${POSTGRES_DB}'
    command: configure
    depends_on:
      - tests-pg
