name: Create and publish a Docker image

on:
  release:
    types: [published]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - registry: ghcr.io
            target: app-image
            image: ghcr.io/${{ github.repository }}
          - registry: ghcr.io
            target: swagger-ui-image
            image: ghcr.io/${{ github.repository }}_swagger_ui

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the container registry
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20
        with:
          registry: ${{ matrix.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81
        with:
          images: ${{ matrix.image }}

      - name: Build and push Docker images
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0
        with:
          context: .
          target: ${{ matrix.target }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
